# Generated by Django 3.2.25 on 2024-10-01 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField()),
                ('id', models.AutoField(db_column='visitor_id', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('id_card', models.IntegerField()),
                ('pic', models.CharField(max_length=255)),
                ('vendor', models.CharField(max_length=255)),
                ('check_in_date', models.DateTimeField()),
                ('check_out_date', models.DateTimeField()),
                ('company', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('mobile_phone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('person_to_visit_name', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='visitor_images/')),
                ('status', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'visitor',
            },
        ),
    ]
