# Generated by Django 3.2.25 on 2024-10-10 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='check_out_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
