# Generated by Django 3.2.25 on 2024-10-11 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0002_alter_visitor_check_out_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField()),
                ('id', models.AutoField(db_column='destination_id', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'destination',
            },
        ),
    ]
