# Generated by Django 3.2.25 on 2024-10-12 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0003_destination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
